In [1]:
print("Hello world!")

Hello world!

In [2]:
import pandas as pd

In [3]:
%pip install pandas

Requirement already satisfied: pandas in /media/shanmukha/DATA1/Acads/Sem_8/AI-for-cybersecurity/lab2-PE-Malware-Detection/.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /media/shanmukha/DATA1/Acads/Sem_8/AI-for-cybersecurity/lab2-PE-Malware-Detection/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /media/shanmukha/DATA1/Acads/Sem_8/AI-for-cybersecurity/lab2-PE-Malware-Detection/.venv/lib/python3.10/site-packages (from pandas) (2025.3)
Requirement already satisfied: numpy>=1.22.4 in /media/shanmukha/DATA1/Acads/Sem_8/AI-for-cybersecurity/lab2-PE-Malware-Detection/.venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in /media/shanmukha/DATA1/Acads/Sem_8/AI-for-cybersecurity/lab2-PE-Malware-Detection/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /media/shanmukha/DATA1/Acads/Sem_8/AI-for-cybersecurity/lab2-PE-Malware-Detection/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
%pip install numpy

Requirement already satisfied: numpy in /media/shanmukha/DATA1/Acads/Sem_8/AI-for-cybersecurity/lab2-PE-Malware-Detection/.venv/lib/python3.10/site-packages (2.2.6)
Note: you may need to restart the kernel to use updated packages.

In [6]:
df = pd.read_csv('../data/PE_Features.csv')
df.head()

,NumberOfSections,NumberOfSymbols,TimeDateStamp,Characteristics,AddressOfEntryPoint,SizeOfInitializedData,SizeOfUnInitializedData,CheckSum,DllCharacteristics,PackedFlag,NumberOfImportedDlls,NumberOfImportedFunctions,FileCategory
0,12,0,1405441897,8450,291713,133120,5632,854318,0,0,12,264,0
1,12,0,1405441399,8450,5201,7168,1024,65672,0,0,2,42,0
2,11,0,1405441375,8450,23249,36864,5632,142750,0,0,4,103,0
3,12,0,1405441383,8450,77937,48640,5632,284722,0,0,6,150,0
4,12,0,1405441399,8450,115009,57344,5632,321124,0,0,5,127,0

In [7]:
df.describe()

,NumberOfSections,NumberOfSymbols,TimeDateStamp,Characteristics,AddressOfEntryPoint,SizeOfInitializedData,SizeOfUnInitializedData,CheckSum,DllCharacteristics,PackedFlag,NumberOfImportedDlls,NumberOfImportedFunctions,FileCategory
count,800.000000,8.000000e+02,8.000000e+02,800.00000,8.000000e+02,8.000000e+02,8.000000e+02,8.000000e+02,800.000000,800.000000,800.000000,800.000000,800.000000
mean,4.751250,3.122395e+07,1.191786e+09,3686.83000,2.087095e+05,2.036623e+05,5.595092e+04,4.574598e+06,13162.005000,0.045000,6.691250,114.347500,0.475000
std,2.928326,2.100580e+08,2.401405e+08,8244.42945,5.856385e+05,1.378668e+06,3.182079e+05,1.233004e+08,16134.844051,0.207434,11.343799,144.729627,0.499687
min,1.000000,0.000000e+00,0.000000e+00,15.00000,4.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,0.000000e+00,1.129375e+09,271.00000,6.818500e+03,7.168000e+03,0.000000e+00,0.000000e+00,0.000000,0.000000,2.000000,22.000000,0.000000
50%,4.000000,0.000000e+00,1.208112e+09,271.00000,2.275150e+04,2.227200e+04,0.000000e+00,6.612100e+04,0.000000,0.000000,5.000000,65.500000,0.000000
75%,5.000000,0.000000e+00,1.306410e+09,783.00000,7.432400e+04,8.192000e+04,0.000000e+00,1.269732e+05,32768.000000,0.000000,9.000000,132.000000,1.000000
max,28.000000,1.652354e+09,4.023211e+09,41358.00000,4.821608e+06,3.570637e+07,4.808704e+06,3.487624e+09,44032.000000,1.000000,254.000000,1113.000000,1.000000